### ISSUE TITLE
ImportError: cannot import name 'validate_call' from 'pydantic'

### ISSUE THREAD

**Issue by hkpD** [papuSpartan/stable-diffusion-webui-auto-tls-https#18]
Hello,

I am receiving the following error when trying to launch webUI with your TLS extension active: 
**ImportError: cannot import name 'validate_call' from 'pydantic' (C:\Users\user\Desktop\stable-diffusion-webui\venv\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)**

Automatic1111 autolaunches http://127.0.0.1:7860 and everything still works. 

Would you happen to have any idea what is happening here?

```
checkout_result: Your branch is up to date with 'origin/master'.

[Auto-Photoshop-SD] Current Branch.
branch_result: * master

[Auto-Photoshop-SD] Fetch upstream.
fetch_result:
[Auto-Photoshop-SD] Pull upstream.
pull_result: Already up to date.
ReActor preheating... Device: CUDA
Launching Web UI with arguments: --theme=dark --ckpt-dir=F:\models\Stable-diffusion --lora-dir=F:\models\Lora --vae-dir=F:\models\VAE
No module 'xformers'. Proceeding without it.
python_server_full_path:  C:\Users\user\Desktop\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.11.1, num models: 9
2023-12-05 10:42:56,411 - ControlNet - INFO - ControlNet v1.1.419
ControlNet preprocessor location: C:\Users\user\Desktop\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-12-05 10:42:56,504 - ControlNet - INFO - ControlNet v1.1.419
10:42:56 - ReActor - STATUS - Running v0.5.1
*** Error loading script: auto_tls.py
    Traceback (most recent call last):
      File "C:\Users\user\Desktop\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\user\Desktop\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\user\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-auto-tls-https\scripts\auto_tls.py", line 29, in <module>
        import certipie
      File "C:\Users\user\Desktop\stable-diffusion-webui\venv\lib\site-packages\certipie\__init__.py", line 1, in <module>
        from certipie.api.main import app, router
      File "C:\Users\user\Desktop\stable-diffusion-webui\venv\lib\site-packages\certipie\api\__init__.py", line 1, in <module>
        from .cert import router
      File "C:\Users\user\Desktop\stable-diffusion-webui\venv\lib\site-packages\certipie\api\cert.py", line 12, in <module>
        from ..core import create_auto_certificate, create_csr, create_private_key
      File "C:\Users\user\Desktop\stable-diffusion-webui\venv\lib\site-packages\certipie\core.py", line 22, in <module>
        from pydantic import Field, FilePath, validate_call
    ImportError: cannot import name 'validate_call' from 'pydantic' (C:\Users\user\Desktop\stable-diffusion-webui\venv\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)

---
Loading weights [e48ca7f826] from F:\models\Stable-diffusion\epiCPhotoGasm\epicphotogasm_v1.safetensors
Creating model from config: C:\Users\user\Desktop\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: sdp... done.
Model loaded in 2.4s (load weights from disk: 0.7s, create model: 0.6s, apply weights to model: 0.9s, calculate empty prompt: 0.1s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
COMMANDLINE_ARGS does not contain --api, API won't be mounted.
Startup time: 18.3s (prepare environment: 6.2s, import torch: 3.0s, import gradio: 1.0s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.6s, setup codeformer: 0.1s, load scripts: 3.1s, create ui: 2.6s, gradio launch: 0.5s).

```

**Comment by papuSpartan** [comment]
It looks like maybe pydantic is older than what the certipie library is requiring? I didn't specify an explicit version of certipie when making this so it's likely the issue. You might try just downgrading certipie using pip in your venv for now.

**Comment by baselqt** [comment]
same error

**Comment by hkpD** [comment]
Resolution - I ran `pip install certipie==0.1.0` after entering my virtual environment. Now the extension functions normally. 

Thank you for pointing me in the right direction, @papuSpartan
