### ISSUE TITLE
Error loading script: auto_tls.py

### ISSUE THREAD

**Issue by dylanh724** [papuSpartan/stable-diffusion-webui-auto-tls-https#20]
On start:

```bash
Launching Web UI with arguments: --xformers --no-half --listen --enable-insecure-extension-access
*** Error loading script: auto_tls.py
    Traceback (most recent call last):
      File "C:\repos\common\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\repos\common\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\repos\common\stable-diffusion-webui\extensions\stable-diffusion-webui-auto-tls-https\scripts\auto_tls.py", line 29, in <module>
        import certipie
      File "C:\repos\common\stable-diffusion-webui\venv\lib\site-packages\certipie\__init__.py", line 1, in <module>
        from certipie.api.main import app, router
      File "C:\repos\common\stable-diffusion-webui\venv\lib\site-packages\certipie\api\__init__.py", line 1, in <module>
        from .cert import router
      File "C:\repos\common\stable-diffusion-webui\venv\lib\site-packages\certipie\api\cert.py", line 12, in <module>
        from ..core import create_auto_certificate, create_csr, create_private_key
      File "C:\repos\common\stable-diffusion-webui\venv\lib\site-packages\certipie\core.py", line 22, in <module>
        from pydantic import Field, FilePath, validate_call
    ImportError: cannot import name 'validate_call' from 'pydantic' (C:\repos\common\stable-diffusion-webui\venv\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)
```

**Comment by dylanh724** [comment]
To add, this seems to be related to someone else's issue:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5150

One day, it just stopped working. When removed, --listen no longer works (no local networked device can access it, anymore).

**Comment by dylanh724** [comment]
To add, I tried:

1. Removing the extension and deleting the extension dir
2. Reload the webui
3. Go to the extensions tab and refresh the list; click "install" for this plugin
4. Automatic can no longer auto-install this; perhaps it's because it hasn't been updated in a long time and now requires a new arg?

```bash
*** Error completing request
*** Arguments: ('https://github.com/papuSpartan/stable-diffusion-webui-auto-tls-https.git', ['ads', 'localization', 'installed'], 0, 'https') {}
    Traceback (most recent call last):
      File "C:\repos\common\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\repos\common\stable-diffusion-webui\modules\ui_extensions.py", line 399, in install_extension_from_index
        ext_table, message = install_extension_from_url(None, url)
      File "C:\repos\common\stable-diffusion-webui\modules\ui_extensions.py", line 344, in install_extension_from_url
        check_access()
      File "C:\repos\common\stable-diffusion-webui\modules\ui_extensions.py", line 23, in check_access
        assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
    AssertionError: extension access disabled because of command line flags
```

**Comment by papuSpartan** [comment]
@dylanh724 are you sure you don't have an option enabled in your sdwui launch args related to this?:
```
 assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
 ```

**Comment by dylanh724** [comment]
Going to close this - I fixed it, but no clue what I did. I just started the process over completely; perhaps some stupid mistake?
