### ISSUE TITLE
Error when Launching Auto TLS https

### ISSUE THREAD

**Issue by CaptainGodual** [papuSpartan/stable-diffusion-webui-auto-tls-https#9]
`Error loading script: auto_tls.py
Traceback (most recent call last):
  File "/home/paperspace/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/paperspace/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/paperspace/stable-diffusion-webui/extensions/stable-diffusion-webui-auto-tls-https/scripts/auto_tls.py", line 28, in <module>
    if not cmd_opts.self_sign:
AttributeError: 'Namespace' object has no attribute 'self_sign'`

I get this when I restart my UI after installing this with the install from url in extensions of SD. Any clue why this would do this?

**Comment by CaptainGodual** [comment]
Seems this issue has resolved it's self after a reboot of the server with SD Webgui
